---
title: "R Notebook - Introduction to Casual Models"
output: html_notebook
---
library(tidyverse)
library(stargazer)

# Clear the environment
rm(list = ls())

# 1. Model 1: Honors class and grades ###

```{r}
# sample 10000 data points
tb <- tibble(
  # ability follows normal distribution
  ability = rnorm(10000),
  # honors is a linear combination of ability and a random factor
  honor = 2*ability + rnorm(10000),
  # grades is a linear combination of honors, ability and a random factor
  grades = 1 + 3*ability - 1*honor + rnorm(10000) 
)

lm_1 <- lm(grades ~ honor, tb)
lm_2 <- lm(grades ~ honor + ability, tb)

stargazer(lm_1,lm_2, type = "text", 
          column.labels = c("Unconditional", 
                            "Conditional"))
```




# 2. Model 2 Discrimination bias: ###

```{r}
# sample 10000 data points
tb <- tibble(
  # female follows binomial distribution of 1 and 0
  female = ifelse(runif(10000)>=0.5,1,0),
  # ability follows normal distribution
  ability = rnorm(10000),
  # discrimination is based on being female
  discrimination = female,
  # occupation is a linear combination of ability, discrimination and a random factor
  occupation = 1 + 2*ability + 0*female - 2*discrimination + rnorm(10000),
  # wage is a linear combination of discrimination, occupation, ability and a random factor
  wage = 1 - 1*discrimination + 1*occupation + 2*ability + rnorm(10000) 
)

lm_1 <- lm(wage ~ female, tb)
lm_2 <- lm(wage ~ female + occupation, tb)
lm_3 <- lm(wage ~ female + occupation + ability, tb)

stargazer(lm_1,lm_2,lm_3, type = "text", 
          column.labels = c("Biased Unconditional", 
                            "Biased",
                            "Unbiased Conditional"))
```


# 3. Model 3: Talent, beauty and movie stars ###

```{r}
library(tidyverse)

set.seed(3444)

star_is_born <- tibble(
  beauty = rnorm(2500),
  talent = rnorm(2500),
  score = beauty + talent,
  c85 = quantile(score, .85),
  star = ifelse(score>=c85,1,0)
)

star_is_born %>% 
  lm(beauty ~ talent, .) %>% 
  ggplot(aes(x = talent, y = beauty)) +
  geom_point(size = 0.5, shape=23) + xlim(-4, 4) + ylim(-4, 4)

star_is_born %>% 
  filter(star == 1) %>% 
  lm(beauty ~ talent, .) %>% 
  ggplot(aes(x = talent, y = beauty)) +
  geom_point(size = 0.5, shape=23) + xlim(-4, 4) + ylim(-4, 4)

star_is_born %>% 
  filter(star == 0) %>% 
  lm(beauty ~ talent, .) %>% 
  ggplot(aes(x = talent, y = beauty)) +
  geom_point(size = 0.5, shape=23) + xlim(-4, 4) + ylim(-4, 4)
```


